// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the ALT-FIT product catalog by keyword, category, gender, and maximum price. Returns shoppable items with prices and affiliate links.",
  inputSchema: {
    query: z.string().trim().optional().describe("Keyword to match against product title or brand."),
    category: z.string().trim().optional().describe("Product category, e.g. top, bottom, shoes, bag."),
    gender: z.string().trim().optional().describe("Target gender, e.g. women, men, unisex."),
    max_price: z.number().positive().optional().describe("Maximum price in the catalog currency."),
    limit: z.number().int().min(1).max(50).optional().describe("Number of products to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, gender, max_price, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let builder = supabase.from("products").select(
      "id, title, brand, price, currency, category, gender, retailer, style_tags, colors, image_url, affiliate_url"
    ).eq("is_active", true).order("last_seen_at", { ascending: false }).limit(limit ?? 10);
    if (query) builder = builder.or(`title.ilike.%${query}%,brand.ilike.%${query}%`);
    if (category) builder = builder.eq("category", category);
    if (gender) builder = builder.eq("gender", gender);
    if (typeof max_price === "number") builder = builder.lte("price", max_price);
    const { data, error } = await builder;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-saved-outfits.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_saved_outfits_default = defineTool2({
  name: "list_saved_outfits",
  title: "List saved outfits",
  description: "List the signed-in user's saved outfits, newest first, including items and total price.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Number of outfits to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_outfits").select("id, name, gender, budget, total_price, items, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { outfits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-outfit.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var OutfitItemSchema = z3.object({
  category: z3.string().trim().describe("Item category, e.g. top, bottom, shoes, bag."),
  product_id: z3.string().trim().optional().describe("Product id from search_products, when the item is from the catalog."),
  name: z3.string().trim().describe("Item name."),
  brand: z3.string().trim().optional(),
  price: z3.number().nonnegative().describe("Item price."),
  image_url: z3.string().trim().optional(),
  affiliate_url: z3.string().trim().optional()
});
var save_outfit_default = defineTool3({
  name: "save_outfit",
  title: "Save outfit",
  description: "Save a new outfit to the signed-in user's ALT-FIT collection.",
  inputSchema: {
    name: z3.string().trim().min(1).describe("Name of the look."),
    gender: z3.string().trim().min(1).describe("Target gender, e.g. women, men, unisex."),
    items: z3.array(OutfitItemSchema).min(1).describe("The pieces that make up the outfit."),
    budget: z3.number().positive().optional().describe("Optional budget for the look.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, gender, items, budget }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const total_price = items.reduce((sum, item) => sum + (item.price ?? 0), 0);
    const { data, error } = await supabase.from("saved_outfits").insert({ user_id: ctx.getUserId(), name, gender, items, budget: budget ?? null, total_price }).select("id, name, gender, budget, total_price, items, created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { outfit: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/get-style-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_style_profile_default = defineTool4({
  name: "get_style_profile",
  title: "Get style profile",
  description: "Get the signed-in user's saved style preferences (favourite styles, budget, sizes) to personalise outfit suggestions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_style_preferences").select("*").limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        {
          type: "text",
          text: data ? JSON.stringify(data) : "No style preferences saved yet for this user."
        }
      ],
      structuredContent: { preferences: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mqpcwdsdyqlxigppjmlc";
var mcp_default = defineMcp({
  name: "style-muse",
  title: "Style Muse",
  version: "0.1.0",
  instructions: "Tools for ALT-FIT, a fashion platform that recreates iconic looks affordably. Use `search_products` to find shoppable catalog items, `get_style_profile` to read the signed-in user's style preferences, `list_saved_outfits` to review their looks, and `save_outfit` to store a new outfit for them.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_style_profile_default, list_saved_outfits_default, save_outfit_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
